SuiteCRM/SuiteDocs

content/developer/3. Working with Beans.adoc

I removed a sentence as a test.

Update 3. Working with Beans.adoc

---

content/developer/23. Appendix C - Automated Testing.adoc

This change add how to setup the automated testing framework.

Adding Automated Testing Documentation

---

content/admin/4.Releases.adoc

Update release notes for 7.8.16, 7.9.15, 7.10.1

Release notes

---

content/admin/4.Releases.adoc

See https://github.com/salesagility/SuiteCRM/pull/5397

Removed reverted PR from release notes

---

content/user/Introduction/_index.es.adoc

Translation of Introduction to UserGuide. Please verify file name

FIX #42 - Translation on Introduction to UserGuide

---

content/admin/4.Releases.adoc

Going forward we should point users to the main site instead of the GitHub repo

Release.adoc

---

content/developer/Appendix C - Automated Testing.adoc

Running the functional and api tests

Fix mistake in command

---

i18n/es.toml

Fix some 'acentos' in spanish translation

---

content/admin/Releases.adoc

Release notes for 7.9.16, 7.8.17, 7.10.2

Update Release notes

---

content/admin/Releases.adoc

Point to the site instead of Github

Update download links

---

content/admin/Releases.adoc

Release notes for 7.8.18, 7.9.17, 7.10.3

Releases.adoc

---

content/_index.es.md

Remove chapter from ES homepage

---

content/developer/Appendix C - Automated Testing.adoc

Documentation for:
- Writing and Running test
- State safe tests
Please do not merge until related PR also merged:
https://github.com/salesagility/SuiteCRM/pull/5718

Test / State safe

---

content/developer/Appendix C - Automated Testing.adoc
content/developer/AutomatedTasks/Sass.adoc
content/developer/AutomatedTasks/TestingEnvironment.adoc
content/developer/AutomatedTasks/_index.en.adoc

This pull request is predicated on https://github.com/salesagility/SuiteCRM/pull/5735/ being merged into the project.
This change adds how to use robo with suitecrm.

Adding automated tasks section to documentation

---

content/blog/creating-custom-field-types.adoc

Add Creating Custom Field Types blog post

Add technical blog post

---

content/developer/Appendix C - Automated Testing.adoc

code coverage infos

---

content/developer/Appendix C - Automated Testing.adoc

Update Appendix C - Automated Testing.adoc

---

content/developer/Introduction.es.adoc
content/developer/Metadata.es.adoc---
content/developer/SuiteCRM Directory Structure.es.adoc
content/developer/Vardefs.es.adoc
content/developer/Views.es.adoc
content/developer/Working with Beans.es.adoc

This is work in progress... we have translated from **Introduction** to **View**.

Developer guide translated into Spanish

---

content/developer/Vardefs.adoc

Add an explanation about how to set default values for date, datetime and datetimecombo.

Setting default values on date like fields

---

content/developer/API/version-8/Customization.adoc

Implementation in PR https://github.com/salesagility/SuiteCRM/pull/6372

APIv8 customization (latest)

---

content/developer/Logic Hooks.adoc

Change Job Queue chapter reference to Scheduled Tasks with link.  (Easier to follow in online docs.)

Change Job Queue chapter reference to Scheduled Tasks

---

content/developer/Appendix C - Automated Testing.adoc

Documentation for SuiteCRM PR https://github.com/salesagility/SuiteCRM/pull/6417

How to: Testing Imap

---

content/admin/Administration Panel/Studio.adoc

Data Types

---

content/developer/AutomatedTasks/_index.en.adoc

Fixes #167.
I also enamed the page to mention Robo so it's easier to find in the documentation and made some other minor changes.

Add some documentation for writing custom Robo tasks in SuiteCRM.

---

content/community/contributing-to-docs/guidelines.adoc
content/community/contributing-to-docs/translate.adoc

New page with guidelines for Docs contributions.

Docs guidelines

---

content/developer/automatedtasks/CodingStyle.adoc

Add documentation for PR: https://github.com/salesagility/SuiteCRM/pull/6186

Robo task documentation

---

content/user/introduction/User Interface/In-line Editing.adoc

Correcting the warning condition

Update In-line Editing.adoc

---

content/user/Security Suite (Groups).adoc

A wrong word and couple of semantic improvements

Update Security Suite (Groups).adoc

---

content/developer/Entry Points.adoc

Update Entry Points.adoc

---

content/community/contributing-code/Bugs.adoc

Updates the contributing code section to explain which branches to use when creating a pull request.

Update pull request process

---

content/admin/releases/7.10.x/_index.en.adoc

Small fix for a broken link I noticed on the 7.10.x release notes.

Fixed broken link on 7.10.x release notes

---

content/community/contributing-code/Bugs.adoc

Complimentary PR to #249 with a few examples of possible flow charts to help show where to direct pull requests.

PR process flow chart

---

content/admin/releases/7.10.x/_index.en.adoc
content/admin/releases/7.8.x/_index.en.adoc

Add CVE link that was removed during the release notes refactor.

Fix missing CVE

---

content/admin/releases/7.10.x/_index.en.adoc
content/admin/releases/7.11.x/_index.en.adoc
content/admin/releases/7.8.x/_index.en.adoc

Release notes update

---

content/admin/Compatibility Matrix.adoc

Compatibility Matrix for PHP 7.3

---

content/developer/Appendix C - Automated Testing.adoc

This is a companion PR to https://github.com/salesagility/SuiteCRM/pull/7352

Remove Demo test suite from Automated Testing documentation.

---

content/developer/automatedtesting/_index.en.adoc

Needed to update the docs to account for some recent changes in SuiteCRM.
- Changes to how ChromeDriver is installed and run: https://github.com/salesagility/SuiteCRM/pull/7345
- Changes to how the user is supposed to set up a local test environment and the removal of Selenium envs: https://github.com/salesagility/SuiteCRM/pull/7433
cc: @Dillon-Brown @pgorod

Update Automated Testing documentation.

---

content/developer/automatedtesting/_index.en.adoc

Update the test commands to use the provided Robo tasks that were added in https://github.com/salesagility/SuiteCRM/pull/7374

Update automated testing docs with Robo commands.

---

content/admin/releases/7.8.x/_index.en.adoc

Fix layout of 7.8.2 release notes.

7.8 release notes fix

---

content/admin/releases/7.10.x/_index.en.adoc

Release Notes for 7.10.19
Included new Format.

Release Notes 7.10.19

---

content/community/Code of Conduct.adoc

This is to provide clearly guidelines on how we aim to encourage members of the community to conduct themselves within SuiteCRM places and with each other.

Revision of Code of Conduct

---

content/admin/releases/7.10.x/_index.en.adoc
content/admin/releases/7.11.x/_index.en.adoc

Add release notes for 7.10.x and 7.11.x

Release notes aug

---

content/user/suitecrm-analytics/Getting Started.adoc

Add the default username and password information

Update Getting Started.adoc

---

content/admin/administration-panel/Google Maps.adoc

Update Google Maps.adoc

---

content/developer/Extension Framework.adoc

Removed typo from Extension Framework documention

---

content/admin/releases/7.10.x/_index.en.adoc
content/admin/releases/7.11.x/_index.en.adoc

I was initially only going to fix one of these, then I noticed a bunch of them had incorrect issue references.
Also fixed a typo :)

Fix incorrect links to issues/PRs in release notes.

---

content/developer/api/Developer-setup-guide/JSON-API.adoc

Closes #252. I didn't updated the path because I think this is another PR matter, as many paths are broken.

Resolves #252 - Fix logout request method

---

content/developer/api/API-4_1.adoc

Changed the sentence to how it should have been in the first place.

Typo fixes

---

content/developer/Further Resources.adoc

The older SugarCRM links were being redirected to the new urls, so i replaced them with the new ones.
also added https to the links while i was at it.

Updated SugarCRM links which were being redirected

---

content/community/contributing-code/Bugs.adoc
content/community/contributing-code/Features.adoc
content/community/contributing-code/Test Pull Requests.adoc

Update Reference - 7.8 -> 7.10

UPDATED DOCUMENTATION(update reference)

---

content/admin/Troubleshooting and Support.adoc
content/admin/administration-panel/search/elasticsearch/Command Line Tools.adoc
content/admin/administration-panel/search/elasticsearch/Introduction.adoc
content/admin/administration-panel/search/elasticsearch/Set up Elasticsearch.adoc
content/admin/administration-panel/search/elasticsearch/Troubleshooting.adoc
content/blog/SuiteCRM-nice-relationships.adoc
content/blog/creating-custom-field-types.adoc

Hi there, 
I made some updates to the documentation by adding grammar edits and also correcting spelling or capitalisation errors. 
I hope this helps!

Updated documentation by adding spelling/grammar edits.

---

content/admin/Advanced Configuration Options.adoc
content/admin/installation-guide/Downloading & Installing.adoc
content/admin/installation-guide/Using the Upgrade Wizard.adoc
content/admin/suitecrm-analytics/SCRM-Analytics.adoc
content/developer/Exceptions and Localization.adoc
content/developer/Extension Framework.adoc

Made some updates to the documentation by adding grammar edits as well as correcting various spelling errors and other typos for the sake of improved readability.

Updated documentation by fixing mistakes

---

content/community/contributing-code/Bugs.adoc
content/community/contributing-code/Coding Standards.adoc

Fix typo in content

---

content/admin/releases/7.10.x/_index.en.adoc
content/admin/releases/7.11.x/_index.en.adoc

Adds the WIP Release notes for SuiteCRM Release

WIP: Updatereleasenotes

---

content/admin/releases/7.10.x/_index.en.adoc
content/admin/releases/7.11.x/_index.en.adoc

Was a bit daft and forgot to update the release date before the release notes where merged

Resolve issues with release notes

---

content/admin/releases/7.10.x/_index.en.adoc
content/admin/releases/7.11.x/_index.en.adoc

Adds the security CSVs for the existing release notes

Add security CSVs

---

content/user/modules/Confirmed-Opt-In-Settings.adoc
content/user/modules/LawfulBasis.adoc

See #294 
I am not sure this was what was intended...

Resolves #294 - GDPR clarifications

---

content/admin/installation-guide/Using the Upgrade Wizard.adoc
content/admin/releases/7.10.x/_index.en.adoc
content/admin/releases/7.11.x/_index.en.adoc
static/css/theme-suitecrm.css

Should:
- Add release notes for both 7.11 and 7.10 releases
- Fix site CSS issue where the navbar is larger than search
- Fix site CSS issue where guide header is out of line
Please let me know if you encounter any issues

Feb20releasenotes

---

content/admin/releases/7.11.x/_index.en.adoc

Updating CVEs for security issues fixed.

Updating Release Notes with confirmed CVEs

---

content/admin/releases/7.10.x/_index.en.adoc

Mirror the 7.11.x release applicable to the 7.10.x version

Updating Release Notes with CVEs

---

content/community/raising-issues/Issue Raising.adoc
content/community/raising-issues/Raising Issues.adoc
content/community/raising-issues/Types of Issue Labels.adoc
content/community/raising-issues/Types of Pull Request Labels.adoc
content/community/raising-issues/_index.en.adoc

https://github.com/salesagility/SuiteDocs/issues/384

Label Layout

---

content/developer/api/Developer-setup-guide/JSON-API.adoc

Docs was wrong in relationship section and hard to understand in the filter section. Swagger file is also wrong at relationship POST, but I don't know where to change it.

Update Relationship JSON Docs

---

content/developer/api/Developer-setup-guide/Getting Available Resources.adoc

To display correct path since prev path not in router setup of PHP's scripts

API - Update Getting Available Resources.adoc

---

content/community/Code of Conduct.adoc

Include more definition of what is appropriate especially if from other communities.
This commit is from a recent review of our code of conduct violations and agreed (the moderator team on the forums) that it helps provide clearer definition of what attitude and actions are acceptable.

Update Code of Conduct.adoc

---

layouts/partials/search.html
static/js/lunr.multi.js
static/js/lunr.ru.js
static/js/lunr.stemmer.support.js
static/js/search.js

See https://github.com/matcornic/hugo-theme-learn/issues/365

Fix search with cyrillic characters

---

content/developer/api/Developer-setup-guide/JSON-API.adoc

The id for creating Module shouldn't be there since it could be auto generated

URL not working until Api/ is add

---

content/user/advanced-modules/Reports.adoc

Visible HTML tags <br/> removed from bullet points

Minor documentation update to Reports.adoc

---

content/developer/automatedtasks/Sass.adoc

According to https://github.com/salesagility/SuiteDocs/issues/450#issuecomment-765015752

Fix #450 Update Sass.adoc, change underscore to dash

---

content/admin/releases/7.10.x/_index.en.adoc
content/admin/releases/7.11.x/_index.en.adoc

Update the Docs to have the new Update Patch

Update the Docs to have the Upgrade Patch

---

content/8.x/admin/installation-guide/Downloading & Installing.adoc

- Add notes above development dependencies
- Add note about running install script without having to pass options
- Add notes about having to create the database before running the install command
- Add notes about setting the webroot to /public
- Add notes about enabling mod_rewrite in apache

Update Install docs

---

content/admin/releases/7.10.x/_index.en.adoc
content/admin/releases/7.11.x/_index.en.adoc

Update 7.10/11 Release Notes

---

content/admin/Compatibility Matrix.adoc
content/admin/releases/7.10.x/_index.en.adoc
content/admin/releases/7.11.x/_index.en.adoc

- Fixes link formatting
- Updated compatbility matrix for PHP 7.4 + Mysql 8

Update release notes + Compatibility matrix

---

content/8.x/developer/development-install-guide.adoc

- Specify folder where the permissions command should be executed

Update developer install guide

---

content/8.x/developer/development-install-guide.adoc

- Update install steps to take into account the unified composer.json file
- Add notes for previous versions

Update dev install guide for unified composer

---

content/8.x/admin/Compatibility Matrix.adoc
content/8.x/admin/installation-guide/Upgrading.adoc
content/8.x/admin/releases/8.0-beta/_index.en.adoc

Pushes new release notes and fixes the wrong type of notices used in 2 locations

Add new release notes for 8Beta2

---

content/developer/api/Developer-setup-guide/JSON-API.adoc

Update to the JSON and Portal Page

Update to API

---

content/admin/releases/7.10.x/_index.en.adoc
content/admin/releases/7.11.x/_index.en.adoc

This is Release Notes for v7.11.20 & 7.10.31

Release Notes - 7.11.20 & 7.10.31

---

content/8.x/admin/releases/8.0-beta/_index.en.adoc

This is the release notes for SuiteCRM Beta 3

Release Notes for Suite 8 beta 3

---

content/8.x/admin/Compatibility Matrix.adoc
content/8.x/developer/development-install-guide.adoc

This PR is to update the Compatibility Matrix for Beta 2 + 3 as well as update some commands on the Install Guide

Update Beta Install Guide and Compatibility Matrix

---

content/admin/releases/7.10.x/_index.en.adoc
content/admin/releases/7.11.x/_index.en.adoc

These are the release notes for 7.10.32 + 7.11.21

Release Notes for 7.10.32 7.11.21

---

content/8.x/admin/installation-guide/Upgrading.adoc

- Add  steps on how to upgrade from Beta 3 to RC
- Add general upgrade steps

Add SuiteCRM 8 upgrade docs

---

content/8.x/admin/releases/8.0/_index.en.adoc

add alias
fix RC reference/link

Update Suite 8 Release Notes

---

content/8.x/_index.en.adoc

Remove Beta from the SuiteCRM 8 guide title

Remove Beta From Guide Title

---

content/8.x/admin/releases/8.0/_index.en.adoc

Update
Add Horizontal bar chart extensions to the Extension Framework
TO
Add extension support for chart widgets to the Extension Framework

Update Chart Extension comment

---

content/admin/Compatibility Matrix.adoc

Update Compatibility MySQL

---

content/8.x/admin/releases/8.0/_index.en.adoc
content/admin/releases/7.10.x/_index.en.adoc
content/admin/releases/7.12.x/_index.en.adoc
content/developer/api/API-4_1.adoc

Add Credits and another CVE that was missed
Add json formatting requirements

Update CVE Number and Credits & Json Formatting update

---

content/8.x/admin/releases/8.1/_index.en.adoc
content/admin/releases/7.12.x/_index.en.adoc

Release Notes - 8.1.3 + 7.12.7

Release Notes - 8.1.3 + 7.12.7

---

content/user/introduction/User Interface/Home Page.adoc

Update Home Page.adoc

---

content/user/introduction/User Interface/Navigation Elements.adoc

Update Navigation Elements.adoc

---

content/user/introduction/User Wizard.adoc

Some tweaks to the content of the page

Update User Wizard.adoc

---

content/developer/Theme/sass.adoc

Update the Sass documentation to have the correct commands.

Update Sass Documentation

---

content/developer/api/Developer-setup-guide/Configure Authentication.adoc
content/developer/api/Developer-setup-guide/Getting Available Resources.adoc
content/developer/api/Developer-setup-guide/JSON-API.adoc
content/developer/api/Developer-setup-guide/SuiteCRM_V8_API_Set_Up_For_Postman.adoc

Reorder the API contents so that the API is setup properly before attempting to call endpoints.
Update and fix the documentation for finding Swagger docs.

Update API docs and change contents order

---

content/developer/Logic Hooks.adoc

Add documentation to address the change in https://github.com/salesagility/SuiteCRM/pull/7325

add after_load_user logic hook

---

content/8.x/admin/installation-guide/Legacy-Migration.adoc

fixed link to Session Configuration

---

content/8.x/developer/extensions/frontend/logic/field-logic/fe-extensions-update-value-backend.adoc

Previously they didnt follow the style of the rest of the page

changed enumeration of headers

---

content/8.x/admin/installation-guide/Upgrading.adoc

$ ./bin/console/ clear:cache
-bash: ./bin/console/: Not a directory

error in command

---

content/developer/api/Developer-setup-guide/Configure Authentication.adoc

I added documentation, request payloads, and responses for the refresh_token grant.

updated configureAuthentication.adoc

---

content/admin/installation-guide/Downloading & Installing.adoc

Added "Notes about PHP configuration" in regards to the session.name PHP configuration directive.

Update Downloading & Installing.adoc

---

content/admin/installation-guide/_index.en.adoc

Understanding the motivation for the fork is important here

Add note that SugarCRM was discontinued

---

content/8.x/admin/installation-guide/webserver-setup-guide.adoc

Per comments, I found the same typo repeated. Changed in my master.

Updated fix of typos (got em all this time)

---

content/user/advanced-modules/PDFTemplates.adoc

See the issue: 
https://github.com/salesagility/SuiteDocs/issues/610

Fix #610 - Issue about Page user/advanced-modules/PDFTemplates.adoc

---

content/8.x/admin/installation-guide/running-the-cli-installer.adoc

See the issue: 
https://github.com/salesagility/SuiteDocs/issues/624

Fix #624 - Issue about Page 8.x/admin/installation-guide/running-the-cli-installer.adoc

---

content/8.x/admin/releases/8.6/_index.en.adoc
content/admin/releases/7.14.x/_index.en.adoc

SuiteCRM 7.14.5 Release Notes
SuiteCRM 8.6.2 Release Notes

SuiteCRM 7.14.5, 8.6.2 Release Notes 

---

content/developer/database-schema.adoc

The Recreated Community PR. 
Credits to @DamienAssursi and @srcengine
Many thanks for your contribution!

Updated database-schema.adoc

---

content/developer/api/Developer-setup-guide/JSON-API.adoc

Fix API relationship referencing `relatedModule` instead of `linkFieldName`

Fix V8 API relationship reference

---

content/8.x/admin/Compatibility Matrix.adoc

Update Compatibility Matrix for 8.9

Update Compatibility Matrix
