- content/community/contributing-code/Contributor Agreement.adoc
Removed a dead link to the old contributors license agreement and replaced it with clahub. Also removed details regarding the old agreement link that are no longer relevant.
> Updated Contributor Agreement.adoc

- content/developer/API/API-8.adoc
Examples were not correctly being displayed:
Also the filter examples needed to be escaped, as asciidoc was not displaying them correctly.
These changes correct the issue
> API 8 - Escaping operators and fixing examples

- content/developer/API/API-8.adoc
Yet another attempt to fix the formatting in the examples for the API documentation
> Fixing examples in API-8

- .gitignore
- content/developer/API/JSON API Error Object.adoc
- content/developer/Error Messages.adoc
- content/developer/Exceptions and Localization.adoc
- content/developer/JSON API Error Object.adoc
- content/developer/Translate strings.adoc
Documentation added for:
- json api error object
- error messages
- translation for exceptions
- translations for strings
Please do not merge it until if related PR also merged into SuiteCRM repository:
https://github.com/salesagility/SuiteCRM/pull/5528
> json api error object, error messages, translation for exceptions, translations for texts

- content/developer/API/version-8/Configure Authentication.adoc
The scopes are not yet implemented, however we have defined some of the scopes in the OAuth2, passing the wrong scope will cause authentication to block the request.
> Update Configure Authentication.adoc

- content/developer/Module Installer.adoc
The `install_defs` key should actually be `installdefs`. The example manifest in the Appendix actually uses the correct key.
> Fix typo in manifest information.

- content/developer/Scheduled Tasks.adoc
$emailSettings is undeclared and raises a warning.
$mailer->FromName = $emailSettings['from_name'];
> example references undeclared variable

- content/community/contributing-code/Bugs.adoc
The documentation didn't explain on how to branch off of one of the hotfix branches.
The fact that the created fork does not display these branches makes it hard to find out how to create such a branch. Creating such a branch from the forked master leads to very complicated pull requests.
I also included a simple push command to origin, as origin is mandatory when branching off of an upstream branch.
> Add git commands on how to branch from an upstream branch

- content/community/contributing-code/Coding Standards.adoc
Updates the code-standards page for copyright header to be for the year 2019.
> Update the code-standards copyright header for 2019

- content/developer/Vardefs.adoc
This wasn't documented but it definitely works in SuiteCRM, so I've added it. 
Changes this page: https://docs.suitecrm.com/developer/vardefs/
The actual code in SuiteCRM where the multienum type is defined: https://github.com/salesagility/SuiteCRM/blob/ef1b41965c056937894dd3018d3b149c9c25a9a9/include/SugarFields/Fields/Multienum/SugarFieldMultienum.php
> Document the multienum type in the Vardefs docs.

- content/developer/api/version-8/Configure Authentication.adoc
- Updated the Oauth2 authentication configuration page to point towards the new V8 access_token path
- Removed 'scope' which is currently not implemented in the V8 API.
- Removed refresh_token from client_credentials. See Oauth2 docs and issue reference for details.
Issue reference: https://github.com/salesagility/SuiteCRM/issues/6141
Further context: https://github.com/salesagility/SuiteCRM/issues/7083
Oauth2 docs: https://oauth2.thephpleague.com/
Oauth2 RFC: https://tools.ietf.org/html/rfc6749
> Update Oauth2 auth

- content/admin/Compatibility Matrix.adoc
Add support for PHP 7.3. This should only be merged after https://github.com/salesagility/SuiteCRM/pull/7290.
> Compatibility Matrix for PHP 7.3

- content/developer/Appendix C - Automated Testing.adoc
- Remove functional test documentation (functional tests are non-existent).
- Remove Codeception unit test documentation (they're replaced by PHPUnit).
- Improved formatting for tables.
- Removed references to BrowserStack, as far as I know no contributors use it so the documentation is likely out-of-date and adds unnecessary complexity.
I'd like to remove Selenium as well, but I don't know if anyone uses it? The documentation still doesn't mention Chrome WebDriver or `composer install`, I need to make more updates to the docs so they can actually be used to set up testing locally.
Also, the state checker documentation should probably be moved to a separate file.
> Update Automated Testing documentation.

- content/developer/Appendix C - Automated Testing.adoc
- content/developer/automatedtesting/TestingEnvironment.adoc
- content/developer/automatedtesting/Writing Tests.adoc
- content/developer/automatedtesting/_index.en.adoc
- Miscellaneous wording/punctuation improvements to the automated testing setup docs.
- Create an automated testing directory
- Split 'Writing Tests' into a separate file to simplify the main automated testing documentation.
- Move `TestingEnvironment` to the Automated Testing directory.
> Split automated testing documentation into multiple files

- content/developer/automatedtesting/_index.en.adoc
This PR does a few things:
- Adds proper setup instructions for the test suite.
- Previously, the documentation didn't mention anything about setting up the database, the Apache server, the CRM install process, or the necessity of running ChromeDriver.
- It didn't explicitly state how to perform the API SQL dumps.
- Reorganizes the automated testing documentation to be a bit simpler and explain the setup process first, at the top of the page. It's now organized so the user can follow the instructions from top to bottom.
- Splits Docker usage into its own section.
- Move the PATH instructions to the bottom of the page under "Other tips" for simplicity.
- Various miscellaneous wording improvements.
This PR only mentions things that are currently available in at least the hotfix-7.10.x …
> Add proper test setup instructions to Automated Testing documentation

- content/developer/Appendix A - Code Examples.adoc
Without this value the sugarbean class will be expecting a string instead of an array and since the custom/modules/Cases/IncidentUtils.php returns an array it won't work without this directive
> Missing "generate_select" => true,

- content/admin/releases/7.10.x/_index.en.adoc
- content/admin/releases/7.11.x/_index.en.adoc
I'm not sure how this should be formatted so I've only done this for the 7.10 release notes. They can be copied into 7.11 if we're satisfied with their formatting/placement.
Based on https://github.com/salesagility/SuiteCRM/pull/7591#issuecomment-512908367
> Add a note about the Smarty breaking change to the 7.10.20 release notes

- content/developer/api/API-4_1.adoc
The old version-8 page is a combination of both developer-setup-guide and postman-setup-guide page so I linked to main API page.
https://github.com/salesagility/SuiteDocs/issues/355
> Fixed broken link to v8 API

- content/admin/administration-panel/search/elasticsearch/Command Line Tools.adoc
Full index value on robo is 0, and partial is 1.
> Fix incorrect instruction on indexing section

- content/community/contributing-code/Coding Standards.adoc
- content/community/contributing-code/Test Pull Requests.adoc
- Fixed a broken link.
- Updated/Fixed coding standards.
- Added a small section to mention SASS rebuild.
One other thing I noticed was the cleanup directions involving:
```
* or in security groups remove the option from the vardefs and remove
// to ensure that modules created and deployed under CE will continue to function under team security if the instance is upgraded to PRO
```
Not sure if this is still relevant or can be safely removed so I've just left it as is for now.
> A few small fixes for the community guide

- content/admin/Advanced Configuration Options.adoc
- content/admin/releases/7.10.x/_index.en.adoc
- content/admin/releases/7.11.x/_index.en.adoc
- layouts/shortcodes/ghcontributors.html
- fixes icons
- shortens GitHub contributors lists tremendously
- a few other removals of unnecessary `pass:`
> Use Shortcodes instead of "pass:" direct HTML hacks

- content/community/contributing-code/Contributor Agreement.adoc
CLAHub is down and the service is no longer available as it was deleted.
Fixes: #466
> Fix broken link in Contributor Agreement

- content/developer/api/Developer-setup-guide/JSON-API.adoc
Pull Request https://github.com/salesagility/SuiteCRM/pull/7277 adds the ability to retrieve modules and fields for a module. It doesn't appear this was ever documented.
> Add documentation for module meta data in V8 API

- content/developer/api/Developer-setup-guide/JSON-API.adoc
Previous example commands to generate OAuth2 keys are complete and can be typed directly in a terminal as written. The generate a new "OAUTH2 encryption key" command line requires "php -r" at the beginning and a novice would probably not know to do this without further research or experience.
The proposed change matches the example found at: https://oauth2.thephpleague.com/v5-security-improvements/
> Update JSON-API.adoc (Generate OAuth2 Encryption Key command line)

- content/8.x/developer/development-install-guide.adoc
- Replace prod mode shell build command reference with dev mode. All frontend builds need to be done in same mode
- Move suitecrm:app:install call to end of the install process
> Update developer install guide

- content/8.x/developer/development-install-guide.adoc
- Remove mentions to running composer with `--no-dev` as that may lead into errors, if one is not familiar with the process
- Add a note explaining that the `pscss` was added as a dev dependecy
> Updade Suite 8 developer install guide

- content/admin/administration-panel/search/elasticsearch/Set up Elasticsearch.adoc
SuiteCRM 7.12 requires Elasticsearch 7 and fails with version 5.6. This was deployed here https://github.com/salesagility/SuiteCRM/pull/9171
Related forum message... https://community.suitecrm.com/t/elasticsearch-throw-type-is-missing-and-no-index-is-populated/83511/4
> Update Set up Elasticsearch.adoc

- content/developer/api/Developer-setup-guide/Getting Available Resources.adoc
the documentation [here](https://docs.suitecrm.com/developer/api/developer-setup-guide/json-api/) uses suitecrm.url to point to the server while this documentation site uses pathtoserver changed this to make it more uniform across the docs
> changed website variable

- content/admin/administration-panel/search/elasticsearch/Set up SuiteCRM.adoc
As written here the scheduled task configuration for elastic search is missing in the documentation:
https://community.suitecrm.com/t/elastic-search-cron-job/67205/8
> Add scheduled task configuration for Elasticsearch

- content/8.x/admin/installation-guide/webserver-setup-guide.adoc
I think just leaving them in there doesnt make it clear that you should add it to the existing one therefore the wording should be changed
> removed dots from vhost configurations

- content/admin/administration-panel/Emails/Email.adoc
Broken links. These are probably showing in htmltest output, but maybe nobody's paying attention to broken links in Docs?
```
12:00:30 PM: ========================================================================
12:00:30 PM: ✘✘✘ failed in 1.326539402s
12:00:30 PM: 848 errors in 429 documents
12:00:30 PM: ---------------------------------------------------------
12:00:30 PM:       1 
12:00:30 PM:     543 hash does not exist
12:00:30 PM:     271 src attribute empty
12:00:30 PM:      33 target does not exist
12:00:30 PM:       1 href blank
```
This output should be clean..., especially the "33 target does not exist" (after this PR fixed a few of them)
I suggest that looking carefully at the htmltest output in Netlify (build log) should be a part of merging PRs into Docs. 
PRs should not be …
> Fix levels in links
